# Generated by Django 4.2.15 on 2024-08-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deva_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
