# Generated by Django 4.2.15 on 2024-08-22 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_no', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('postalcose', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='chef_details',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dish.address'),
        ),
    ]
