# Generated by Django 4.2.15 on 2024-08-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_author_full_name_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
